spring:
  application:
    name: "funny-queue"
  datasource:
    url: jdbc:postgresql://localhost:5432/funny-queue
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  security:
    user:
      name: user
      password: pass

server:
  servlet:
    context-path: /fq
