spring:
  application:
    name: "funny-queue"
  datasource:
    url: jdbc:postgresql://localhost:5432/funny-queue
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  security:
    user:
      name: user
      password: pass

server:
  servlet:
    context-path: /
  port: 8080

logging:
  level:
    liquibase: info
    feign:
      client: info