DROP TABLE IF EXISTS slots;
DROP TABLE IF EXISTS breaks;
DROP TABLE IF EXISTS queues;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(128) NOT NULL,
    email       VARCHAR(128) NOT NULL,
    password    VARCHAR(128) NOT NULL,
    enabled     BOOLEAN      NOT NULL,
    create_date TIMESTAMP,
    last_update TIMESTAMP
);


CREATE TABLE user_roles
(
    user_id INTEGER NOT NULL,
    role    VARCHAR(255),
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);


CREATE TABLE queues
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(128) NOT NULL,
    user_id         INTEGER      NOT NULL,
    work_start_time TIME         NOT NULL DEFAULT '09:30:00',
    work_end_time   TIME         NOT NULL DEFAULT '18:30:00',
    slot_time       INTEGER      NOT NULL DEFAULT 30,
    enabled         BOOLEAN      NOT NULL DEFAULT 'true',
    create_date     TIMESTAMP,
    last_update     TIMESTAMP
);


CREATE TABLE breaks
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(128) NOT NULL,
    queue_id    INTEGER      NOT NULL,
    start_time  TIME         NOT NULL,
    end_time    TIME         NOT NULL,
    create_date TIMESTAMP,
    last_update TIMESTAMP
);


CREATE TABLE slots
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue_id    INTEGER   NOT NULL,
    user_id     INTEGER   NOT NULL,
    date_time   TIMESTAMP NOT NULL UNIQUE,
    create_date TIMESTAMP,
    last_update TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (queue_id) REFERENCES queues (id) ON DELETE CASCADE
);