DROP TABLE IF EXISTS records;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;


CREATE TABLE users
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(128) NOT NULL,
    password    VARCHAR(128) NOT NULL,
    name        VARCHAR(128) NOT NULL,
    enabled     BOOLEAN      NOT NULL,
    create_date TIMESTAMP,
    last_update TIMESTAMP
);


CREATE TABLE user_roles
(
    user_id INTEGER NOT NULL,
    role    VARCHAR(255),
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);


CREATE TABLE public.records
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        INTEGER   NOT NULL,
    queue_owner_id INTEGER   NOT NULL,
    date_time      TIMESTAMP NOT NULL UNIQUE,
    create_date    TIMESTAMP,
    last_update    TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (queue_owner_id) REFERENCES users (id) ON DELETE CASCADE
);